### ISSUE TITLE
errors of 001preparation

### ISSUE THREAD

**Issue by dlmubs** [MEhrenmueller/DataModeling#1]
trivial but easy to fix

 1
run 
CREATE SCHEMA demo;
CREATE SCHEMA PowerBI; in separate query to avoid error **'create view' must be the first statement in a query batch**.

2 
move query the CREATE OR ALTER VIEW [PowerBI].[FactResellerSales] above to avoid undeclared quote in CREATE OR ALTER VIEW [PowerBI].[DimProduct]

**Comment by MEhrenmueller** [comment]
Fixed.
And thanks for hunting these two bugs, @dlmubs !
